//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractProductB.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_ABSTRACTPRODUCTB_H)
#define _ABSTRACTPRODUCTB_H


class AbstractProductB
{
public:
    virtual ~AbstractProductB();
	void operation();
protected:
	AbstractProductB();
};

#endif  //_ABSTRACTPRODUCTB_H
