//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractProductA.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "AbstractProductA.h"

AbstractProductA::~AbstractProductA()
{

}

void AbstractProductA::operation()
{

}

AbstractProductA::AbstractProductA()
{

}

