//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractProductA.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_ABSTRACTPRODUCTA_H)
#define _ABSTRACTPRODUCTA_H


class AbstractProductA
{
public:
    virtual ~AbstractProductA();
	void operation();
protected:
	AbstractProductA();
};

#endif  //_ABSTRACTPRODUCTA_H
