//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractProductB.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "AbstractProductB.h"

AbstractProductB::~AbstractProductB()
{

}

void AbstractProductB::operation()
{

}

AbstractProductB::AbstractProductB()
{

}

