//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstactFactory.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "AbstractFactory.h"
#include "AbstractProductA.h"
#include "AbstractProductB.h"

AbstractFactory::~AbstractFactory()
{

}

AbstractFactory::AbstractFactory()
{

}

