//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteFactory2.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_CONCRETEFACTORY2_H)
#define _CONCRETEFACTORY2_H

#include "AbstractFactory.h"

class ConcreteFactory2 : public AbstractFactory
{
public:
	ConcreteFactory2();
	~ConcreteFactory2();
	AbstractProductA* createProductA();
	AbstractProductB* createProductB();
};

#endif  //_CONCRETEFACTORY2_H
