//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteFactory1.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "ConcreteFactory1.h"
#include "ProductA2.h"
#include "ProductB2.h"

ConcreteFactory1::ConcreteFactory1()
{

}

ConcreteFactory1::~ConcreteFactory1()
{

}

AbstractProductA* ConcreteFactory1::createProductA()
{
    return new ProductA2();
}

AbstractProductB* ConcreteFactory1::createProductB()
{
    return new ProductB2();
}

