//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductA1.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_PRODUCTA1_H)
#define _PRODUCTA1_H

#include "AbstractProductA.h"

class ProductA1 : public AbstractProductA
{
public:
	ProductA1();
	~ProductA1();
	void operation();
};

#endif  //_PRODUCTA1_H
