//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductB2.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "ProductB2.h"
#include <iostream>

ProductB2::ProductB2()
{
    std::cout << "ProductB2..." << std::endl;
}

ProductB2::~ProductB2()
{

}

void ProductB2::operation()
{

}

