//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductA2.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_PRODUCTA2_H)
#define _PRODUCTA2_H

#include "AbstractProductA.h"

class ProductA2 : public AbstractProductA
{
public:
	ProductA2();
	~ProductA2();
	void operation();
};

#endif  //_PRODUCTA2_H
