//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductB1.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_PRODUCTB1_H)
#define _PRODUCTB1_H

#include "AbstractProductB.h"

class ProductB1 : public AbstractProductB
{
public:
	ProductB1();
	~ProductB1();
	void operation();
};

#endif  //_PRODUCTB1_H
