//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductB2.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_PRODUCTB2_H)
#define _PRODUCTB2_H

#include "AbstractProductB.h"

class ProductB2 : public AbstractProductB
{
public:
	ProductB2();
	~ProductB2();
	void operation();
};

#endif  //_PRODUCTB2_H
