//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductA1.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "ProductA1.h"
#include <iostream>

ProductA1::ProductA1()
{
    std::cout << "ProductA1..." << std::endl;
}

ProductA1::~ProductA1()
{

}

void ProductA1::operation()
{

}

