//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductA2.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "ProductA2.h"
#include <iostream>

ProductA2::ProductA2()
{
    std::cout << "ProductA2..." << std::endl;
}

ProductA2::~ProductA2()
{

}

void ProductA2::operation()
{

}

