//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductB1.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "ProductB1.h"
#include <iostream>

ProductB1::ProductB1()
{
    std::cout << "ProductB1..." << std::endl;
}

ProductB1::~ProductB1()
{

}

void ProductB1::operation()
{

}

