//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Singleton
//  @ File Name : Singleton.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "Singleton.h"
#include <iostream>

Singleton* Singleton::m_instance = 0;

Singleton::Singleton()
{
    std::cout << "Singleton..." << std::endl;
}

Singleton::~Singleton()
{

}

Singleton* Singleton::instance()
{
    if( 0 == m_instance )
    {
        /* 如果使用多线程: */
        /* 详情参考C++设计新思维泛型编程与设计模式之应用 */
        /* 第6章Singleton实现技术的第6.9节生活在多线程世界 */

        // Guard myGuard(m_lock);
        // if( 0 == m_instance )
        // {
        m_instance = new Singleton();
        // }
    }

    return m_instance;
}
