name "3D虚拟建模工具箱"
version 3.1 

treeCopy "3DTools" to $scripts

run "d.ms"

move "install.ms" to $startupScripts
move "WelcomePanel.mse" to $Scripts\3DTools
move "welcome.bmp" to $Scripts\3DTools
move "3DFunctions.mse" to $Scripts\3DTools
move "3D虚拟建模工具箱-*.mse" $Scripts\3DTools
move "裁剪工具*.mse" to $Scripts\3DTools
move "拖贴图自动命名*.mse" to $Scripts\3DTools

run "$startupScripts\\install.ms"
drop "$startupScripts\\install.ms"