//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FactoryPatter
//  @ File Name : ConcreteFactory.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_CONCRETEFACTORY_H)
#define _CONCRETEFACTORY_H

#include "Factory.h"

class ConcreteFactory : public Factory
{
public:
	ConcreteFactory();
	~ConcreteFactory();
	Product* createProduct();
};

#endif  //_CONCRETEFACTORY_H
