//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FactoryPatter
//  @ File Name : ConcreteFactory.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "ConcreteFactory.h"
#include "ConcreteProduct1.h"

#include <iostream>
using namespace std;


ConcreteFactory::ConcreteFactory()
{
    cout << "ConcreteFactory..." << endl;
}

ConcreteFactory::~ConcreteFactory()
{

}

Product* ConcreteFactory::createProduct()
{
    return new ConcreteProduct1();
}

