//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FactoryPatter
//  @ File Name : ConcreteProduct1.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_CONCRETEPRODUCT1_H)
#define _CONCRETEPRODUCT1_H

#include "Product.h"

class ConcreteProduct1 : public Product
{
public:
    ConcreteProduct1();
    ~ConcreteProduct1();

	void operation();
};

#endif  //_CONCRETEPRODUCT1_H
