//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FactoryPatter
//  @ File Name : ConcreteProduct1.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "ConcreteProduct1.h"
#include <iostream>

using namespace std;

ConcreteProduct1::ConcreteProduct1()
{
    cout << "ConcreteProduct1..." << endl;
}

ConcreteProduct1::~ConcreteProduct1()
{

}

void ConcreteProduct1::operation()
{
    cout << "operation in ConcreteProduct1" << endl;
}

