//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FactoryPatter
//  @ File Name : ConcreteProduct2.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "ConcreteProduct2.h"

ConcreteProduct2::ConcreteProduct2()
{

}

ConcreteProduct2::~ConcreteProduct2()
{

}

void ConcreteProduct2::operation()
{

}

