//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FactoryPatter
//  @ File Name : ConcreteProduct2.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_CONCRETEPRODUCT2_H)
#define _CONCRETEPRODUCT2_H

#include "Product.h"

class ConcreteProduct2 : public Product
{
public:
	ConcreteProduct2();
	~ConcreteProduct2();
	void operation();
};

#endif  //_CONCRETEPRODUCT2_H
