//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FactoryPatter
//  @ File Name : Factory.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "Factory.h"
#include "Product.h"

Factory::~Factory()
{

}

Factory::Factory()
{

}

