//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FactoryPatter
//  @ File Name : Factory.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_FACTORY_H)
#define _FACTORY_H

class Product;

class Factory
{
public:
    virtual ~Factory() = 0;
	virtual Product* createProduct() = 0;

protected:
    Factory();
};

#endif  //_FACTORY_H
