//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FactoryPatter
//  @ File Name : Product.h
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#if !defined(_PRODUCT_H)
#define _PRODUCT_H


class Product
{
public:
    virtual ~Product() = 0;
    void operation();

protected:
	Product();
};

#endif  //_PRODUCT_H
