//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FactoryPatter
//  @ File Name : Product.cpp
//  @ Date : 2014/7/15
//  @ Author : www.newdebug.com
//
//


#include "Product.h"
#include <iostream>
using namespace std;

Product::Product()
{
    cout << "Product..." << endl;
}

Product::~Product()
{

}

void Product::operation()
{

}
